apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  restartPolicy: Always
  containers:
  - name: web-server
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    command:
      - /bin/sh
      - -c
      - hostname > /usr/share/nginx/html/index.html; nginx -g "daemon off;"
