apiVersion: v1
kind: Pod
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  restartPolicy: Always
  containers:
  - name: hostname
    image: bosornd/hostname
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /started
        port: 80
      periodSeconds: 5
      failureThreshold: 2
    livenessProbe:
      httpGet:
        path: /live
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5

