apiVersion: v1
kind: Pod
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  restartPolicy: Always
  containers:
  - name: hostname
    image: bosornd/hostname
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    command:
    - sh
    - -c
    - touch /tmp/healthy; node server.js
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
