apiVersion: v1
kind: Pod
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  restartPolicy: Always
  initContainers:
  - name: init
    image: busybox
    command:
    - touch
    - /tmp/healthy
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  containers:
  - name: hostname
    image: bosornd/hostname
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  volumes:
  - name: tmp
    emptyDir: {}
