apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  restartPolicy: Always
  containers:
  - name: web-server
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: updater
    image: busybox
    command:
    - /bin/sh
    - -c
    - n=0; while :; do n=$((n+1)); echo $n > /html/index.html; sleep 10; done
    volumeMounts:
    - name: html
      mountPath: /html
  volumes:
  - name: html
    emptyDir: {}