apiVersion: v1
kind: Pod
metadata:
  name: init
  labels:
    app: init
spec:
  restartPolicy: Never
  containers:
  - name: init
    image: bosornd/git
    imagePullPolicy: IfNotPresent
    command:
    - git
    - clone
    - https://github.com/bosornd/test-web.git
    - /html
    volumeMounts:
    - name: html
      mountPath: /html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: html
