apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs
spec:
  replicas: 1
  serviceName: nfs
  selector:
    matchLabels:
      svc: nfs
  template:
    metadata:
      labels:
        svc: nfs
    spec:
      containers:
      - name: nfs
        image: registry.k8s.io/volume-nfs
        imagePullPolicy: IfNotPresent
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /exports
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  selector:
    svc: nfs
  type: LoadBalancer
  # sessionAffinity: ClientIP
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
