apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: node-problem-detector
        image: registry.k8s.io/node-problem-detector:v0.1
        imagePullPolicy: IfNotPresent