apiVersion: v1
kind: Pod
metadata:
  name: count-db-master
  labels:
    app: count-db-master
spec:
  restartPolicy: Always
  containers:
  - name: count-db-master
    image: redis
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-count-db-master
---
apiVersion: v1
kind: Service
metadata:
  name: count-db-master
spec:
  selector:
    app: count-db-master
  type: ClusterIP
  # sessionAffinity: ClientIP
  ports:
  - port: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-count-db-master
spec:
  resources:
    requests:
      storage: 1Mi
  accessModes:
  - ReadWriteMany
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - cp /data/dump.rdb /backup/dump-`date +%y-%m-%d`.rdb
            volumeMounts:
            - name: data
              mountPath: /data
            - name: backup
              mountPath: /backup
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data-count-db-master
          - name: backup
            persistentVolumeClaim:
              claimName: backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
spec:
  resources:
    requests:
      storage: 1Mi
  accessModes:
  - ReadWriteMany
