apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: bosornd/counter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: COUNT_DB_URL_FOR_READ
          valueFrom:
            configMapKeyRef:
              name: config
              key: COUNT_DB_URL_FOR_READ
        - name: COUNT_DB_URL_FOR_WRITE
          valueFrom:
            configMapKeyRef:
              name: config
              key: COUNT_DB_URL_FOR_WRITE
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            configMapKeyRef:
              name: config
              key: RABBITMQ_PASS
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: ClusterIP
  # sessionAffinity: ClientIP
  ports:
  - port: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50